version: 2.1

orbs:
  azure-acr: circleci/azure-acr@0.2.1
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
jobs:
  build--test-linting: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # Setup environnement + install dependencies
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: linting
          command: flake8
  containerize:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # Setup environnement + install dependencies
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -t quentinmetro/ocfp13:$TAG .
          docker logout
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push quentinmetro/ocfp13:$TAG
  deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: |
          az acr import --name ocfp13 --source docker.io/quentinmetro/ocfp13:$TAG --image quentinmetro/ocfp13:$TAG --username $DOCKER_USER --password $DOCKER_PASS
  

# Invoke jobs via workflows
workflows:
  sample: 
    jobs:
      - build--test-linting
      - containerize:
            requires:
              - build--test-linting # wait for build--test-linting job to complete successfully before starting
      - deploy:
            requires:
              - build--test-linting
              - containerize
            filters:
              branches:
                only: main # on the branch main only
