version: 2.1

orbs:
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
jobs:
  build--test-linting: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # Setup environnement + install dependecies
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: linting
          command: flake8
  contenerize: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout # Setup environnement + install dependecies
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=$(git rev-parse --short HEAD)
          docker build -t quentinmetro/ocfp13:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push quentinmetro/ocfp13:$TAG
  

# Invoke jobs via workflows
workflows:
  sample: 
    jobs:
      - build--test-linting
      - contenerize:
            requires:
              - build--test-linting # wait for build--test-linting job to complete successfully before starting
      #- deploy:
            #requires:
              #- build--test-linting
            #filters:
              #branches:
                #only: master # on the branch master only
