# Generated by Django 3.0 on 2023-06-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address",
                    reverse_sql="DELETE FROM lettings_address",
                ),
                migrations.RunSQL(
                    sql="INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting",
                    reverse_sql="DELETE FROM lettings_letting",
                ),
                migrations.RunSQL(
                    sql="INSERT INTO profiles_profile SELECT * FROM oc_lettings_site_profile",
                    reverse_sql="DELETE FROM profiles_profile",
                ),
                migrations.RunSQL(
                    sql="DROP TABLE oc_lettings_site_profile",
                ),
                migrations.RunSQL(
                    sql="DROP TABLE oc_lettings_site_address",
                ),
                migrations.RunSQL(
                    sql="DROP TABLE oc_lettings_site_letting",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='letting',
                    name='address',
                ),
                migrations.RemoveField(
                    model_name='profile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Address',
                ),
                migrations.DeleteModel(
                    name='Letting',
                ),
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
        ),
    ]
